---

# credentials to access OpenNebula
user: oneadmin
password: oneadmin

# OpenNebula frontend endpoint
# an empty endpoint will default to http://localhost:2633/RPC2
# endpoint:

# frequency to retrieve metrics in seconds. defaults to 60.
# interval: 60

# FQDN and port to run the exporter on
host: frontend.server.com
port: 9615

# exporter uri to publish on. defaults to /metrics
# path: /metrics

